### ISSUE TITLE
Encoded message/rfc822 attachment not decoded before being parsed

### ISSUE THREAD

**Issue by todd-richmond** [markov2/perl5-Mail-Message#17]
If a MIME msg has an attached message/rfc822, it attempts to create a Message::Body::Nested with it, but the content in this case is base64 encoded and so isn't properly parsed recursively. For us, that means the part is completely skipped - bypassing all analysis
Message.pm has a check for elsif($type eq 'message/rfc822' && !$bodytype->isNested) that converts to a nested object, but doesn't try to decode the input data. Note that MSFT Outlook parses the email correctly

I'm not sure how this should be handled
1) this is an attachment so the sender's request was not to parse it recursively - i.e. should it remain an attached ::Lines object
2) if it should still be parsed, then it needs to start with decoded content. I assume the same bug exists for any transfer encoding

Here is a sample message with the base64 attachment data truncated for easier debugging.
```
Subject: test
Content-Type: multipart/mixed; boundary=BOUND_63F902B74261E3.60363083

--BOUND_63F902B74261E3.60363083
Content-Type: message/rfc822; name="email.eml"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="email.eml"


UmV0dXJuLVBhdGg6IDxzdGVmYW5vLnZpcnppQHZhbGJydW5hLml0Pg0KUmVjZWl2ZWQ6IChxbWFp
bCAyNTY5MyBpbnZva2VkIGJ5IHVpZCA4OSk7IDEzIEZlYiAyMDIzIDEyOjQzOjMxIC0wMDAwDQpS
ZWNlaXZlZDogZnJvbSB1bmtub3duIChIRUxPIG14ZGhmZTAxLmFkLmFydWJhLml0KSAoMTAuMTAu
MTAuMjExKQ0KICBieSBteGRoYmUxMi5hZC5hcnViYS5pdCB3aXRoIFNNVFA7IDEzIEZlYiAyMDIz
IDEyOjQzOjMxIC0wMDAwDQpSZWNlaXZlZDogZnJvbSBzZXJ2ZXIuZHJlYW12aWV3LmNvLmlsIChb
DQo=

--BOUND_63F902B74261E3.60363083--

**Comment by todd-richmond** [comment]
this base64 encoding was invalid according to previous RFC, but with EAI, it makes sense to encode an EAI message with 8bit characters
This was relaxed in section 4.4 of https://datatracker.ietf.org/doc/rfc6533/

**Comment by markov2** [comment]
> this base64 encoding was invalid according to previous RFC, but with EAI, it makes sense to encode an EAI message with 8bit characters This was relaxed in section 4.4 of https://datatracker.ietf.org/doc/rfc6533/ Based on this RFC, it looks like #1 option won't fly and #s is required. It wasn't obvious to me how to ensure the Body::Nested reading would use decoded data

Sorry, I do not agree with you on this argument.  Changes to the interpretation of message/rfc822 will be added in its applicable RFC.  The section you refer to speaks about "message/global" and
```
Note that [RFC6532] relaxed a restriction from MIME [RFC2046]
regarding the use of Content-Transfer-Encoding in new "message"
subtypes.
```
where I think **new** is crucial.  When I look at RFC6532 https://datatracker.ietf.org/doc/rfc6532 section 3.5, it only overrides the **restriction of disallowing** content-transfer-encoding on message/ types from RFC2046, to be able to use it in message/global.  It do not see where it permits it on any other message type.

So: my initial study on this issue says: illegal message.  However: who is producing these incorrect messages?  Maybe, Mail::Box should support it anyway (be forgiving in what you accept).

**Comment by todd-richmond** [comment]
The wording is very convoluted as it states message/global must be handled as message/rfc822 which to me means the relaxing happens for all

Note that as far as a multipart/report [RFC6522] container is
   concerned, message/global-delivery-status, message/global, and
   message/global-headers MUST be treated as equivalent to message/
   delivery-status, message/rfc822, and text/rfc822-headers. 

Regardless, email clients are reading this as relaxed and so this email came from a real world example (just trimmed for testing). Outlook also properly decodes the content and displays as expected so we need to dive into it which means MSFT also reads the RFC as relaxed

Definitely agree with being forgiving in acceptance since in our case, you can easily put virus's and spam in a MIME part that will happily be displayed to users, but unseen by Mail::Box

**Comment by markov2** [comment]
I have found a very cowardous approach, but gladly also simple to implement.  Parts with message/rfc822 but also a Content-Transfer-Encoding will be treated just like an application/pdf.  So, when encountered, you will have to parse them yourself... something like:
```perl
if($part->contentType eq 'message/rfc822')
{    my $nested = Mail::Message->read($part->body->decoded);
}
```

Released in 3.013 today.

**Comment by todd-richmond** [comment]
patch works for me - thx! Closing as fixed

**Comment by todd-richmond** [comment]
during our regression testing, we found an example of a PGP signed email file being forwarded that failed because the attached signature used to be part of the original $message->parts() and now is skipped over because you don't recurse through the eml. 

Not recursing does seem correct, but there is still an inconsistency that might cause concern for some. If CTE is specified, then the message/RFC822 is left whole and if not, it is parsed into the parts list. For PGP, we had a 7bit CTE and so it is no unparsed

Again, I think the behavior is correct, but want to make sure as I go back and validate all our test cases. This is one part of a multipart/mixed message with text, html and rfc822

```
Content-Type: message/rfc822;
        name="pgp-signed.eml"
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment;
        filename="pgp-signed.eml"
