### ISSUE TITLE
Mail::Message::Field::Address - long phrases with brackets

### ISSUE THREAD

**Issue by abeverley** [markov2/perl5-Mail-Message#2]
Phrases with brackets do not appear to be encoded correctly as quoted-printable by Mail::Message::Field::Address. This only seems to happen under certain circumstances, with particularly long phrases. The following demonstrates the problem:

```
my $f = Mail::Message::Field::Address->new(
    address => 'andy@example.com',
    phrase  => 'John Smith with a long long long long phrase (via test list)',
);

my $new = Mail::Message::Field::Address->parse("$f");
print $new->phrase; # Prints ?=
```

**Comment by markov2** [comment]
Ah. stupid of me: accidentally removed the last test in the final clean-up  Thanks for reporting.

**Comment by abeverley** [comment]
Thanks Mark.
